import type { MetadataRoute } from "next";
import { siteOrigin } from "@/lib/site-url";

/**
 * /robots.txt — generated by the App Router at build time.
 *
 * Everything public is crawlable; the two areas that must not be indexed are
 * the API surface and the member account page (per-user, gated, no SEO value).
 * The auth utility pages (/login, /signup, /reset-password, /forgot-password)
 * are thin and carry no crawl value, so they are excluded from the sitemap but
 * not blocked — blocking them would be a needless directive with no benefit.
 *
 * The Sitemap line uses the canonical origin so a Preview build never points
 * Google at a Preview URL. Launch checklist Phase 1 (SEO basics) requires this.
 */
export default function robots(): MetadataRoute.Robots {
  const base = siteOrigin();
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: ["/api/", "/account"],
    },
    sitemap: `${base}/sitemap.xml`,
    host: base,
  };
}
