import type { MetadataRoute } from "next";
import { siteOrigin } from "@/lib/site-url";
import { articles } from "@/app/blog/articlesData";

/**
 * /sitemap.xml — generated by the App Router at build time.
 *
 * Lists the public, indexable marketing routes plus every blog article. What is
 * deliberately EXCLUDED, and why:
 *   • gated / per-user pages: /account, and the /api/* surface (robots blocks
 *     these too);
 *   • auth utility pages: /login, /signup, /reset-password, /forgot-password
 *     — thin, no SEO value;
 *   • /learn/course/[module] — the module pages render only a locked outline to
 *     the public; the sales page /learn/course is the one to index;
 *   • the legacy off-nav pages /articles, /framework, /journeys — Open decision
 *     D-3 (Known issue 4): they link to pages that do not exist and may be
 *     removed, so they are not offered to Google.
 *
 * The origin comes from siteOrigin() so a Preview build never emits Preview
 * URLs. Add a new public route here when one ships.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const base = siteOrigin();
  const now = new Date();

  // Public, indexable marketing routes.
  const publicRoutes = [
    "/",
    "/about",
    "/book",
    "/premium",
    "/learn",
    "/learn/course",
    "/assess",
    "/start",
    "/tools",
    "/practice",
    "/speaking",
    "/enterprise",
    "/community",
    "/newsletter",
    "/podcast",
    "/stories",
    "/blog",
    "/contact",
    "/privacy",
    "/terms",
  ];

  const pageEntries: MetadataRoute.Sitemap = publicRoutes.map((path) => ({
    url: `${base}${path === "/" ? "" : path}`,
    lastModified: now,
    changeFrequency: path === "/" ? "weekly" : "monthly",
    priority: path === "/" ? 1 : 0.7,
  }));

  const blogEntries: MetadataRoute.Sitemap = articles.map((a) => ({
    url: `${base}/blog/${a.slug}`,
    lastModified: now,
    changeFrequency: "yearly",
    priority: 0.5,
  }));

  return [...pageEntries, ...blogEntries];
}
