-- 0001_entitlements.sql — public.entitlements: the PRODUCTION BASELINE, captured, not designed.
--
-- Captured from unretire-prod (ref hcjivvlwxltyiycfbttc) on 2026-08-28 through the read-only
-- supabase-prod-readonly MCP (decision D-11): pg_catalog / information_schema queries only — no row data.
-- Sprint S2.5 (docs/sprint-prompts/S2.5-environment-parity.md); change record
-- docs/database-changes/0001-entitlements.md.
--
-- Do NOT edit this file by hand. Any change to this table ships as a NEW numbered migration
-- (docs/ENVIRONMENT-PARITY.md §5.6; docs/templates/SUPABASE-CHANGE-TEMPLATE.md).
-- Applied to unretire-test ONLY (S2.5, owner-authorised). On unretire-prod this definition already exists —
-- it is the source of this file, never its target. Paired down file: 0001_entitlements.down.sql
-- (schema only; it never restores data; it is never run against Production).
--
-- Production facts preserved verbatim (and why they matter — docs/ENVIRONMENT-PARITY.md §5.1):
--   * status admits THREE values: 'active', 'canceled', 'expired'. The code writes only the first two;
--     'expired' was undocumented before this capture.
--   * UNIQUE (user_id, product) — the webhook's upsert (onConflict: "user_id,product") depends on it.
--   * Exactly ONE policy: authenticated users may SELECT their own rows. There is NO write policy —
--     every write comes from the service-role client, which bypasses RLS.
--   * updated_at is maintained by trigger entitlements_updated_at → public.set_updated_at().
--   * There is NO index on stripe_subscription_id in production (§5.1 expects one; recorded as a
--     difference in the change record — not added here, because a capture must not improve on its source).
--   * Table and function grants are Supabase's defaults for objects created in public
--     (postgres / anon / authenticated / service_role — all privileges, gated by RLS); they are applied by the
--     project's default privileges, so they are not restated here.

create table if not exists public.entitlements (
  id                     uuid        primary key default gen_random_uuid(),
  user_id                uuid        not null references auth.users (id) on delete cascade,
  product                text        not null,
  status                 text        not null default 'active',
  stripe_customer_id     text,
  stripe_subscription_id text,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  constraint entitlements_product_check
    check (product = any (array['course'::text, 'premium'::text])),
  constraint entitlements_status_check
    check (status = any (array['active'::text, 'canceled'::text, 'expired'::text])),
  constraint entitlements_user_id_product_key unique (user_id, product)
);

alter table public.entitlements enable row level security;

drop policy if exists "Users can read their own entitlements" on public.entitlements;
create policy "Users can read their own entitlements"
  on public.entitlements
  for select
  to authenticated
  using (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists entitlements_updated_at on public.entitlements;
create trigger entitlements_updated_at
  before update on public.entitlements
  for each row execute function public.set_updated_at();
