-- 0002_book_downloads.sql — public.book_downloads: the PRODUCTION BASELINE, verified against the committed file.
--
-- Verified against unretire-prod (ref hcjivvlwxltyiycfbttc) on 2026-08-28 through the read-only
-- supabase-prod-readonly MCP (decision D-11): pg_catalog / information_schema queries only — no row data.
-- Production matches src/app/account/_book/book_downloads.sql in every respect that file defines (columns,
-- defaults, the doc_type check, UNIQUE (user_id, doc_type), the ON DELETE CASCADE foreign key, RLS enabled,
-- exactly two PERMISSIVE policies for public — SELECT and INSERT, own rows only — and deliberately NO update
-- or delete policy). That file stays where it is, untouched; from Sprint S2.5 THIS file is the canonical,
-- numbered copy, made idempotent and with production's constraint names spelled out.
-- Sprint S2.5 (docs/sprint-prompts/S2.5-environment-parity.md); change record
-- docs/database-changes/0002-book-downloads.md.
--
-- Do NOT edit this file by hand. Any change ships as a NEW numbered migration (docs/ENVIRONMENT-PARITY.md §5.6).
-- Applied to unretire-test ONLY (S2.5, owner-authorised). On unretire-prod this definition already exists.
-- Paired down file: 0002_book_downloads.down.sql (schema only; never restores data; never run on Production).
-- Grants are Supabase's defaults for objects created in public (applied by default privileges; not restated).

create table if not exists public.book_downloads (
  id            uuid        primary key default gen_random_uuid(),
  user_id       uuid        not null references auth.users (id) on delete cascade,
  doc_type      text        not null,
  downloaded_at timestamptz not null default now(),
  constraint book_downloads_doc_type_check
    check (doc_type = any (array['book'::text, 'workbook'::text])),
  constraint book_downloads_user_id_doc_type_key unique (user_id, doc_type)
);

alter table public.book_downloads enable row level security;

-- Members may read their own download records.
drop policy if exists "own downloads readable" on public.book_downloads;
create policy "own downloads readable"
  on public.book_downloads
  for select
  using (auth.uid() = user_id);

-- Members may record their own download (the unique constraint above is what enforces "once").
drop policy if exists "own downloads insertable" on public.book_downloads;
create policy "own downloads insertable"
  on public.book_downloads
  for insert
  with check (auth.uid() = user_id);

-- Deliberately NO update or delete policy: a download record can never be edited or removed by a member.
